"""initial_schema

Revision ID: 965a4cd46a88
Revises:
Create Date: 2026-09-26 13:27:35.463584

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "965a4cd46a88"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advisoryrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=True),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("recommendation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("citations_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "risk_signals_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("limitations", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_advisoryrecord_farm_id"), "advisoryrecord", ["farm_id"], unique=False
    )
    op.create_table(
        "diseaseanalysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=True),
        sa.Column("crop", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "predicted_class", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diseaseanalysis_farm_id"), "diseaseanalysis", ["farm_id"], unique=False
    )
    op.create_table(
        "externalobservation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=True),
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("capability", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metric_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("numeric_value", sa.Float(), nullable=True),
        sa.Column("string_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_quality", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("freshness", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("observed_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("retrieved_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("raw_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_externalobservation_farm_id"),
        "externalobservation",
        ["farm_id"],
        unique=False,
    )
    op.create_table(
        "farm",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location_query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("primary_crop", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plot_identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "soilreading",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=True),
        sa.Column("nitrogen", sa.Float(), nullable=False),
        sa.Column("phosphorus", sa.Float(), nullable=False),
        sa.Column("potassium", sa.Float(), nullable=False),
        sa.Column("ph", sa.Float(), nullable=False),
        sa.Column("moisture", sa.Float(), nullable=False),
        sa.Column("crop", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "predicted_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("model_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_soilreading_farm_id"), "soilreading", ["farm_id"], unique=False
    )
    op.create_table(
        "climatesnapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("period_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mean_temp_c", sa.Float(), nullable=True),
        sa.Column("total_precip_mm", sa.Float(), nullable=True),
        sa.Column("rainfall_7d_mm", sa.Float(), nullable=True),
        sa.Column("rainfall_14d_mm", sa.Float(), nullable=True),
        sa.Column("rainfall_30d_mm", sa.Float(), nullable=True),
        sa.Column("dry_spell_days", sa.Integer(), nullable=True),
        sa.Column("gdd_cumulative", sa.Float(), nullable=True),
        sa.Column("et0_cumulative", sa.Float(), nullable=True),
        sa.Column("anomalies_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("freshness", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retrieved_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farm.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_climatesnapshot_farm_id"), "climatesnapshot", ["farm_id"], unique=False
    )
    op.create_table(
        "environmentsnapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("pm25", sa.Float(), nullable=True),
        sa.Column("aqi_estimate", sa.Integer(), nullable=True),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.Column("biodiversity_count", sa.Integer(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("freshness", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retrieved_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farm.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_environmentsnapshot_farm_id"),
        "environmentsnapshot",
        ["farm_id"],
        unique=False,
    )
    op.create_table(
        "farmlocation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("district", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("village", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.Column("raw_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farm.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_farmlocation_farm_id"), "farmlocation", ["farm_id"], unique=False
    )
    op.create_table(
        "weathersnapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("humidity_pct", sa.Float(), nullable=True),
        sa.Column("rainfall_mm", sa.Float(), nullable=True),
        sa.Column("wind_speed_kmh", sa.Float(), nullable=True),
        sa.Column("et0_mm", sa.Float(), nullable=True),
        sa.Column("vpd_kpa", sa.Float(), nullable=True),
        sa.Column("soil_temperature_c", sa.Float(), nullable=True),
        sa.Column("soil_moisture_m3m3", sa.Float(), nullable=True),
        sa.Column("gdd", sa.Float(), nullable=True),
        sa.Column("forecast_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("freshness", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retrieved_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farm.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weathersnapshot_farm_id"), "weathersnapshot", ["farm_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weathersnapshot_farm_id"), table_name="weathersnapshot")
    op.drop_table("weathersnapshot")
    op.drop_index(op.f("ix_farmlocation_farm_id"), table_name="farmlocation")
    op.drop_table("farmlocation")
    op.drop_index(
        op.f("ix_environmentsnapshot_farm_id"), table_name="environmentsnapshot"
    )
    op.drop_table("environmentsnapshot")
    op.drop_index(op.f("ix_climatesnapshot_farm_id"), table_name="climatesnapshot")
    op.drop_table("climatesnapshot")
    op.drop_index(op.f("ix_soilreading_farm_id"), table_name="soilreading")
    op.drop_table("soilreading")
    op.drop_table("farm")
    op.drop_index(
        op.f("ix_externalobservation_farm_id"), table_name="externalobservation"
    )
    op.drop_table("externalobservation")
    op.drop_index(op.f("ix_diseaseanalysis_farm_id"), table_name="diseaseanalysis")
    op.drop_table("diseaseanalysis")
    op.drop_index(op.f("ix_advisoryrecord_farm_id"), table_name="advisoryrecord")
    op.drop_table("advisoryrecord")
    # ### end Alembic commands ###
