import type React from "react";

export const ResponsibleAI: React.FC = () => {
  return (
    <div className="space-y-6">
      <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm space-y-4">
        <h1 className="text-2xl font-bold text-gray-900">
          Responsible AI Framework & Data Provenance
        </h1>
        <p className="text-sm text-gray-600">
          AgriGuard AI is designed under strict Responsible AI governance
          principles for smallholder agricultural decision support.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4">
          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-2">
            <h3 className="font-bold text-slate-900 text-sm">
              1. Grounded Advisory & Zero Hallucination
            </h3>
            <p className="text-xs text-slate-600">
              Advisories generated by the LLM layer (IBM Granite / Local
              Fallback) are strictly constrained to retrieved official extension
              documents from ChromaDB. If insufficient evidence is found, the
              system explicitly refuses to fabricate advice and prompts for
              expert consultation.
            </p>
          </div>

          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-2">
            <h3 className="font-bold text-slate-900 text-sm">
              2. Explicit Data Provenance & Quality
            </h3>
            <p className="text-xs text-slate-600">
              Every data point distinguishes among <code>OBSERVED</code>,{" "}
              <code>WEATHER_MODEL</code>, <code>HISTORICAL_CLIMATE</code>,{" "}
              <code>ML_PREDICTION</code>, and <code>SYNTHETIC</code> modes.
              Cached and stale data states are explicitly tagged with provenance
              badges.
            </p>
          </div>

          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-2">
            <h3 className="font-bold text-slate-900 text-sm">
              3. Model Limitations Transparency
            </h3>
            <p className="text-xs text-slate-600">
              The crop disease model (MobileNet) and soil model (XGBoost) are
              prototype models trained on public/synthetic datasets. They are
              explicitly labeled as non-field-validated decision-support
              prototypes rather than certified laboratory diagnostics.
            </p>
          </div>

          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-2">
            <h3 className="font-bold text-slate-900 text-sm">
              4. Qualitative Risk Signals
            </h3>
            <p className="text-xs text-slate-600">
              Environmental risk indicators (fungal pressure, water stress, heat
              stress) output qualitative levels and clear meteorological
              explanations without manufacturing false, uncalibrated probability
              numbers.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResponsibleAI;
